DAYS = [
    {
        "n": 1,
        "date": "2026-09-22",
        "shape": "Session 1 (105 min): discovery (math/data/Python), select entry, open session, first artifact work",
        "facts": "Fresh fixture; empty progress; `sync` derives 49 nodes available.",
        "actions": ["today --minutes 105", "next --minutes 105 --limit 5", "next --show-locked --limit 3",
                    "node × 3 (entry details)", "resources --node-id math entry", "start MATH", "work --minutes 70", "close"],
        "expected": "A beginner could ask the engine for math/data/Python foundations and get walkable entry points.",
        "observed": "Read-only surfaces work, but discovery is id-only: nothing accepts a subject query; `today` and `next` both top-rank an agents-course node (off the beginner arc) every single day of the fortnight.",
        "friction": ["No text/keyword discovery surface exists (`next` takes only minutes/limit/show-locked).",
                     "Learner must already know `programming.python.variables_01`-style ids to see any skill.",
                     "`next` prints a stale command form (`skilltrace session start --node …`) while `today` prints the real one (`skilltrace start …`).",
                     "`next --show-locked` sized a 60-min session and still rendered no locked rows visibly."],
        "uncertainty": "Whether the agents-first ranking is goal-weighting (seed intent) or accidental; real learner intent not measurable from simulation.",
        "quotes": [("Day 1", "recommendations sized"), ("Day 1", "discovery probe: math entry detail")],
    },
    {
        "n": 3,
        "date": "2026-09-24",
        "shape": "Session 2: return to unfinished work, evidence inspection, continued artifact work",
        "facts": "MATH active (in progress); 0/3 evidence; no session open.",
        "actions": ["today", "node MATH", "work MATH (continue)", "eligibility MATH", "close"],
        "expected": "Today foregrounds the unfinished thread; work continues it.",
        "observed": "`node` correctly shows [In progress] and the 0-of-3 bar; `eligibility` reads 0/3 NOT ELIGIBLE. But `work` refuses — a closed session cannot be reopened; returning to unfinished work requires a fresh `start` (a new session record per study day).",
        "friction": ["'Return to unfinished work' has no resume affordance: work requires an open session, so each study day re-`start`s (more sessions, no thread continuity).",
                     "`today` still says 'your best focus today is [agents node]' even with an in-progress node."],
        "uncertainty": "Whether repeated start/close is by design (session = day) — the record trail suggests yes, but the learner-facing copy never says so.",
        "quotes": [("Day 3", "evidence inspection mid-node"), ("Day 3", "today: what is unfinished?")],
    },
    {
        "n": 5,
        "date": "2026-09-26",
        "shape": "Session 3: discovery round 2, second-strand selection, artifact work",
        "facts": "MATH active; PY available; workload warn threshold at 2 active nodes.",
        "actions": ["today", "next --limit 8", "node PY", "resources PY", "start PY", "work PY", "close"],
        "expected": "Second strand opens with a workload warning at the threshold.",
        "observed": "Warning fired exactly: 'this start makes 2 active nodes — at or past the workload warning threshold of 2.' Advisory only; action proceeded.",
        "friction": ["Discovery round 2 again shows the same agents OPTION 1; strand browsing is impossible without ids."],
        "uncertainty": "None for the threshold; ranking behavior carried from Day 1.",
        "quotes": [("Day 5", "open the Python-strand session")],
    },
    {
        "n": 7,
        "date": "2026-09-28",
        "shape": "Session 4: evidence submission + gate judgment readout, next-action readback",
        "facts": "MATH manual gate (learner authority), spec minimum 3 accepted submissions.",
        "actions": ["today", "submit MATH (no verdict)", "submit MATH --accept", "eligibility MATH", "today", "close"],
        "expected": "Submission without a verdict is refused; explicit learner verdict accepted; eligibility readback honest.",
        "observed": "Refusal path is clean and explicit ('manual-authority node requires an explicit verdict … nothing written'). Accept wrote ev…001 (accepted); eligibility read 1/3 accepted, NOT ELIGIBLE. Gate readout matches the learner-authority boundary.",
        "friction": ["The node view says 'It needs 3 accepted submission(s) to pass' — countable, but the learner must find `eligibility` themselves; `today` never mentions evidence progress.",
                     "No open session existed on this day, so `close` refused — a submission day with no artifact work is a session-less day."],
        "uncertainty": "Objective-gate path (check-script judgment) not exercised in the baseline; math/data/Python entry gates are manual.",
        "quotes": [("Day 7", "submit without a manual verdict"), ("Day 7", "scripted learner's manual gate"), ("Day 7", "gate readback")],
    },
]

DAYS += [
    {
        "n": 8,
        "date": "2026-09-29",
        "shape": "Session 5: third-strand selection, artifact work (no-pass session permitted)",
        "facts": "3rd active node crosses the warn-2 threshold again.",
        "actions": ["today", "node SQL", "start SQL", "work SQL --minutes 105", "close"],
        "expected": "Third strand opens; warning repeats; session ends without a pass — no demotion pressure.",
        "observed": "Warning repeated; session closed; SQL stays active at 0/1 evidence. No-pass sessions are unproblematic.",
        "friction": ["Three strands at once is fine mechanically, but no surface summarizes 'you have 3 strands going' outside the workload warning."],
        "uncertainty": "None.",
        "quotes": [("Day 8", "open the SQL-strand session")],
    },
    {
        "n": 10,
        "date": "2026-10-01",
        "shape": "Session 6: blocker/failure handling inside honest-work shape",
        "facts": "PY practice hit reassignment confusion; 3rd active warning expected on start.",
        "actions": ["today", "start PY", "work PY --blocked", "attempt record PY --outcome failed", "blocker create PY", "blockers", "suggest remediation", "close"],
        "expected": "Failed attempt and blocker recorded; remediation pressure appears.",
        "observed": "Both records wrote cleanly (immutable attempt; open blocker listed). `suggest remediation` honestly reported there is no remediation edge covering this blocker and pointed at the ad-hoc action command.",
        "friction": ["Failed attempts are invisible in `today`/`next` — the learner's own failure exists only via `suggest remediation` or raw listings.",
                     "Blocker resolution later requires typing the id `blk.<node>.001` — the learner must copy it from a listing."],
        "uncertainty": "Whether any beginner node has a remediation edge (19 remediation edges exist in the graph; none from the Python entry).",
        "quotes": [("Day 10", "record the failed attempt"), ("Day 10", "name the persistent stuckness"), ("Day 10", "remediation pressure")],
    },
    {
        "n": 12,
        "date": "2026-10-03",
        "shape": "Session 7: return to unfinished work, correction/supersession",
        "facts": "Open blocker on PY; day-7 accepted record ev…001 on MATH.",
        "actions": ["today", "blocker resolve --summary", "remediation create --blocker", "submit --supersedes ev…001 --reason … --accept", "submit --supersedes ev…002 … --accept (depth 2)", "eligibility MATH", "close"],
        "expected": "Correction supersedes the old record; the chain stays as history; eligibility counts only live records.",
        "observed": "Supersession wrote ev…002 then ev…003 (both accepted, chained); the original record was never edited or deleted. Supersede also requires the explicit manual verdict (`--accept`), same as first submission.",
        "friction": ["`today` showed the open blocker line — good; but nothing anywhere shows the correction chain except `report evidence`.",
                     "Session-less day again: no `start` issued, so `close` refused (honest, but the copy doesn't guide)."],
        "uncertainty": "None beyond display gaps.",
        "quotes": [("Day 12", "supersede the day-7 record"), ("Day 12", "supersede the superseding record")],
    },
]

DAYS += [
    {
        "n": 14,
        "date": "2026-10-05",
        "shape": "Session 8: close sessions honestly, final evidence inspection, day report",
        "facts": "MATH 1/3 live accepted (after chain), PY blocker resolved + 1 failed attempt, SQL 0/1, 0 passes — by design.",
        "actions": ["today", "eligibility SQL", "close", "report progress/evidence/blockers", "reviews", "retention status", "analytics velocity/blockers", "health"],
        "expected": "A readable fortnight summary: what moved, what stands, what needs attention.",
        "observed": "Reports are honest and detailed (progress per track, evidence chain, resolved blocker history). `health` rolls up repo diagnostics fine. But learner-facing advisories are misleading at this scale: 'Review completion is below target: 0% (target: 80%)' with zero reviews ever scheduled; evidence coverage 1% reads as failure, though the arc had no passes by contract.",
        "friction": ["Advisory copy doesn't qualify sparse-history baselines (velocity does — it prints a limited-data advisory only in `analytics velocity`).",
                     "No single learner-facing 'Health' view exists: the facts are spread across five commands.",
                     "Report progress 'Currently working on Apply order of operations. Next up: finish active evidence…' — the strongest line in the fortnight, buried in a report."],
        "uncertainty": "Real comprehension/time cannot be measured from automation (contract §7).",
        "quotes": [("Day 14", "progress report"), ("Day 14", "analytics: velocity"), ("Day 14", "health roll-up")],
    },
]
