# Branch-coverage matrix (contract §5). Tuple order:
# id, name, starting facts, actions, expected, observed, friction, candidate, uncertainty, runnable

BRANCHES = [
    ("B01", "Cold start", "Empty fixture, no history", "today/next at 30 and 105 min",
     "Some entry point surfaces", "Agents-course node tops every list at every minutes value",
     "Cold start is goal-biased to agents; beginner arc invisible", "Discovery (rank for subject intent)", "Real cold-start intent unmeasurable", "RUN"),
    ("B02", "Prior learning — pass direct from available", "Fabricated passed node + accepted evidence (hand-authored)", "node/next/today/start on the passed node",
     "Pass respected; start refused or harmless", "Session opened on the passed node with no state line; asserted state stayed passed (verified in store)",
     "No refusal and no explanation when starting a passed node", "—", "Whether a learner would ever try; mastery path untouched", "RUN"),
    ("B03", "Multiple active nodes", "Two closed sessions (2 active)", "start 3rd; today; next",
     "Warning at 3rd; today picks open thread", "Warning fired at 3 exactly; today picks the open-session thread; next still recommends starting the agents node",
     "next ignores active work entirely", "Discovery ranking", "Warn-threshold semantics (warn at 2, fires on 3rd) — as seeded", "RUN"),
    ("B04", "Hard vs soft prerequisites", "Entries available; no passes", "node on soft+hard targets; seed passes; sync; re-node",
     "Hard target locks until prereq passed; soft never blocks", "Exactly that: conditionals [Locked] with named unsatisfied prereq → [Ready to start] after the pass; soft algebra target never locked",
     "None — this works well and reads clearly", "—", "Single-edge observation, not full-graph", "RUN"),
    ("B05", "Insufficient evidence (rejected artifact)", "MATH active, 0 accepted", "submit --reject; eligibility; node; next",
     "Rejected stays rejected; eligibility 0/3", "verdict REJECTED written; eligibility 0/3 accepted; node shows 0 of 3; next unaffected",
     "Rejected record invisible outside report evidence", "Diagnostic analytics (gap visibility)", "—", "RUN"),
    ("B06", "Failed attempts below threshold (2/3)", "2 failed attempts on PY", "suggest remediation; node; next",
     "No remediation pressure below 3", "'nothing to suggest — no active remediation edges' at 2",
     "Failures invisible in learner surfaces", "Diagnostic analytics", "PY has no remediation edge; a node with one could differ (untested)", "RUN"),
    ("B07", "Failed attempts at threshold (3/3)", "3 failed attempts", "suggest remediation; node; next",
     "Remediation edge activates at 3", "Still 'nothing to suggest' — no edge exists from PY",
     "Threshold signal silent without graph edges", "Diagnostic analytics", "Edge-present variant untested here", "RUN"),
    ("B08", "Failed attempts above threshold (4/3)", "4 failed attempts", "suggest remediation; today; eligibility",
     "Pressure saturates, never blocks", "'nothing to suggest'; today unaffected; eligibility untouched by failures",
     "A learner's 4 failures change nothing they can see", "Diagnostic analytics (strongest signal)", "—", "RUN"),
    ("B09", "Blocker lifecycle", "PY active, stuck work", "blocker create/resolve; remediation create/complete; blockers; suggest",
     "Full lifecycle with audit trail", "All steps succeeded; suggest pointed to ad-hoc action; open list cleared after resolve",
     "Ids must be typed by hand (blk.<node>.001)", "—", "—", "RUN"),
    ("B10", "Due/overdue reviews around the 2-day grace boundary", "Fabricated passed SQL + review due 09-24 (hand-authored)", "reviews/suggest reviews/today at due, +1d, +2d, +3d",
     "OVERDUE appears after grace", "reviews flags [OVERDUE] from +1 day; on the due date suggest reviews says 'nothing due — 1 scheduled ahead' while reviews lists it due",
     "Two surfaces disagree on 'due' semantics on the boundary day; today never mentions the due review", "Practice profiles (backlog shape) — negative here", "Boundary defined as due date itself", "RUN"),
    ("B11", "Failed review without demotion", "Fabricated passed SQL + scheduled review", "review complete --outcome unsatisfactory; node; reviews; suggest",
     "State stays passed; failure recorded", "State held [Passed]; review completed unsatisfactory; reviews list empties",
     "After a failed review, nothing points the learner at rework", "Diagnostic analytics; practice profiles", "Mastery-eligibility effect untested", "RUN"),
    ("B12", "Superseding correction chain", "MATH active", "submit v1; v2 supersedes v1; v3 supersedes v2; report evidence; eligibility",
     "Chain preserved; only live records count", "ev…001→002→003 chained; eligibility counts 1/3 (2 superseded excluded); originals never edited/deleted",
     "Chain visible only in report evidence", "—", "—", "RUN"),
]

BRANCHES += [
    ("B13", "Broken / mismatched resource", "khan-arithmetic supports MATH", "verify-resource --broken; resources; resource-report; node; today; replace-resource",
     "Broken marker visible where the learner looks", "resource-report shows [broken]; node view and today show nothing; replace-resource refused ('share no node') — correctly, but leaves the learner with only a dead resource",
     "Broken resource invisible in node view and today; no replacement candidate exists for this node", "Resource deep-verification (negative); sweep scheduling (negative)", "Reachability checks (network) intentionally not run", "RUN"),
    ("B14", "Interrupted / stale session", "Session opened at 20:00, still open next morning", "today (+13h); close --end",
     "Stale warning past 12h; honest close accepted", "today shows open session (~0 min) but no stale-age warning; close --end (fixture-dated) refused as 'in the future' — validated against the real wall clock, not the fixture clock",
     "Stale threshold not surfaced to the learner; close --end cannot operate under a simulated clock", "—", "Real-world close --end works (only wall-clock-validated here)", "RUN (partial)"),
    ("B15", "Duplicate submission", "MATH active", "submit same artifact ×2 accepted + 1 rejected; report; eligibility",
     "New record each time; rejected stays rejected; accepted counted only", "ev…001/002 accepted, 003 rejected; eligibility 2/3",
     "None — exactly the immutable-records doctrine", "—", "—", "RUN"),
    ("B16a", "Sparse history (1 session)", "One 60-min session", "analytics velocity; health; today",
     "Limited-data advisory appears", "'Limited data — fewer than 3 sessions…' advisory fired; velocity/review advisories still printed",
     "Review-completion advisory fires with zero reviews", "Practice profiles (negative)", "—", "RUN"),
    ("B16b", "Established history (3-session line)", "3 sessions across 6 days (fixture-dated where the engine allows)", "analytics velocity; health; today; retention",
     "Full-data line, no limited-data advisory", "Limited-data advisory gone; velocity 1.0 vs target 2; review-completion 0% advisory persists with zero reviews",
     "Same review-completion artifact as B16a", "Practice profiles (review backlog — negative: no backlog builds)", "Engine-written session timestamps still carry real dates (clock gap)", "RUN (partial)"),
    ("B17", "Curriculum edit flips availability; asserted progress holds", "CPF active (closed session); FRA available", "edges.yaml hard edge added; graph impact; sync; node ×2; next; revert; sync",
     "FRA available→locked; CPF active holds; revert restores", "Exactly: FRA [Locked] with named reason; CPF [In progress] untouched; after revert FRA [Ready to start] again",
     "`graph impact` compared the fixture against the real repo's git HEAD (ignores --root isolation); findings meaningless in a fixture", "—", "Impact advisory needs a git-context fixture to test properly", "RUN (graph impact = observed hazard)"),
]

# Candidate–trigger matrix (contract §6). Tuple order:
# n, name, verbatim trigger, positive, negative, boundary, observed, disposition

CANDIDATES = [
    ("1", "Learner-facing diagnostic analytics",
     "a first real blocker or failed assessment attempt (friction to diagnose), or learner demand for the primitive",
     "B06–B08: 2/3/4 failed attempts produce zero learner-visible signal; B11: failed review leaves nothing pointing at rework; B13: broken resource invisible in node view/today; B02: silent session-on-passed",
     "Learner can function without it: blockers/eligibility/report surfaces carry the facts when sought",
     "P-DiagnosticsSim (#285) already shaped the friction surface; this fortnight adds the demand-side evidence shape",
     "Friction exists and is invisible at exactly the trigger's shape; demand is the learner's call on reading this artifact",
     "Reconsideration-supported (demand branch only; first-real-friction branch still needs lived data — learner verdict required)"),
    ("2", "Practice profiles + prompt extraction",
     "a first real review backlog (reviews accumulating under retention pressure)",
     "B10/B11 exercise review flows but no backlog accumulates (no pass by contract)",
     "Zero reviews scheduled all fortnight; a sequencing layer would build nothing",
     "B10 shows the boundary semantics a backlog would stress",
     "Not trippable by simulation, as the contract predicted",
     "Deferral-supported (unchanged trigger; insufficient evidence)"),
    ("3", "Badge issuance",
     "a concrete portfolio consumer demands a badge primitive",
     "—", "—", "—",
     "UNTESTABLE by the fortnight: no consumer, no passed nodes by contract",
     "Insufficient evidence (stays deferred)"),
    ("4", "Tier 3 MC/PKM integrations",
     "fresh-user demand (MC-1/MC-2, PKM-2/3/4) / ecosystem settling (PKM-4); MC-3 no-go by construction; PKM-1 shipped",
     "—", "—", "—",
     "UNTESTABLE: no PKM in use; outreach tests the in-vault variant, not demand",
     "Insufficient evidence (stays deferred)"),
    ("5", "Full gate-runner / scheduler-queue",
     "a concrete Phase 4/5 seed artifact whose objective gates are hand-run often enough to automate; earliest re-check is v2.5 receipt load",
     "B12 chain exercised manual evidence handling, not gate running",
     "All three beginner gates are manual (learner authority) — no objective gate was hand-run in the arc",
     "v2.5 receipt load unchanged",
     "Hand-run load not demonstrated; simulation cannot supply it",
     "Deferral-supported (unchanged; hand-run load unobserved)"),
    ("6", "Verification-sweep scheduling automation",
     "disjunction: demonstrated manual-sweep cadence, a downstream slot needing scheduled checks, or serve/today background-sweep work",
     "B13: broken marker appears only after a manual verify-resource",
     "No sweep cadence demonstrated; single broken-resource incident, manually handled",
     "—",
     "No cadence emerged from the fortnight",
     "Deferral-supported (unchanged)"),
    ("7", "Resource deep-verification (cert metadata, content-hash drift)",
     "a content-drift incident a hash check would have caught, or a host/publisher requiring pinned-content verification",
     "B13 simulates a dead link (reachability), not content drift",
     "No drift incident; no pinned-content host in the arc",
     "—",
     "Trigger untripped; cert-metadata slice remains first if it ever trips",
     "Deferral-supported (unchanged)"),
    ("8", "Portable evidence locator",
     "a second external consumer of evidence records beyond the portfolio export exists",
     "—", "—", "—",
     "UNTESTABLE: no second consumer exists",
     "Insufficient evidence (stays deferred)"),
    ("9", "Default-deny share-profile extensions",
     "a second sharing/export surface demands a privacy posture",
     "—", "—", "—",
     "UNTESTABLE: existing Share profile in force",
     "Insufficient evidence (stays deferred)"),
]
